import { SurveySection } from '../types';
import {
  ESCALA_SATISFACCION,
  MARCAS,
  NO_P7_PRECIO_CERRADO,
  P7_OPCIONES,
  PAISES,
  REGION_ARG,
  REGION_CHI,
  REGION_COL,
  REGION_DEU,
  REGION_PER,
  REGION_POR,
  REGION_PRY,
  REGION_URY,
  SI_F1_PORTUGAL,
  SI_F3_PROSEGUR,
  SI_F4_HOGAR,
  SI_F4_NEGOCIO,
  SI_F5_PRESENCIAL,
  SI_NO_COD,
  SI_P16A,
  SI_P31,
  SI_P32_ECONOMICA,
  SI_P4_NO,
  SI_P45,
  SI_P7_PRECIO,
  evidenciasModule,
  pais,
} from './constants';

const SI_NO_MATRIX = [
  { value: '1', label: 'Sí', labelPt: 'Sim' },
  { value: '2', label: 'No', labelPt: 'Não' },
];

const ESPONT_SOLIC = [
  { value: '1', label: 'Espontáneo', labelPt: 'Espontâneo' },
  { value: '2', label: 'Solicitado', labelPt: 'Solicitado' },
];

export const parte1: SurveySection = {
  id: 'parte-1',
  title: 'Parte 1 — Contacto y evaluación comercial',
  titlePt: 'Parte 1 — Contacto e avaliação comercial',
  description: 'Desde el screening hasta la evaluación de la experiencia (hasta P55).',
  descriptionPt: 'Desde o screening até à avaliação da experiência (até P55).',
  modules: [
    {
      id: 'screening',
      title: 'Screening',
      titlePt: 'Screening',
      description: 'Datos del mystery y ubicación',
      descriptionPt: 'Dados do mystery e localização',
      questions: [
        {
          id: 'f1-pais',
          text: 'F1. ¿En qué país realiza el mystery?',
          textPt: 'F1. Em que país realiza o mystery?',
          type: 'single',
          options: PAISES,
          required: true,
        },
        {
          id: 'f2a-region',
          text: 'F2A. ¿En qué región se encuentra? (Argentina)',
          textPt: 'F2A. Em que região se encontra? (Argentina)',
          type: 'single',
          options: REGION_ARG,
          showIf: pais('1'),
          terminateIf: { questionId: 'f2a-region', values: ['otro'] },
        },
        {
          id: 'f2b-region',
          text: 'F2B. ¿En qué región se encuentra? (Colombia)',
          textPt: 'F2B. Em que região se encontra? (Colombia)',
          type: 'single',
          options: REGION_COL,
          showIf: pais('2'),
          terminateIf: { questionId: 'f2b-region', values: ['otro'] },
        },
        {
          id: 'f2c-region',
          text: 'F2C. ¿En qué región se encuentra? (Perú)',
          textPt: 'F2C. Em que região se encontra? (Perú)',
          type: 'single',
          options: REGION_PER,
          showIf: pais('3'),
          terminateIf: { questionId: 'f2c-region', values: ['otro'] },
        },
        {
          id: 'f2d-region',
          text: 'F2D. ¿En qué región se encuentra? (Chile)',
          textPt: 'F2D. Em que região se encontra? (Chile)',
          type: 'single',
          options: REGION_CHI,
          showIf: pais('4'),
          terminateIf: { questionId: 'f2d-region', values: ['otro'] },
        },
        {
          id: 'f2e-region',
          text: 'F2E. ¿En qué región se encuentra? (Paraguay)',
          textPt: 'F2E. Em que região se encontra? (Paraguay)',
          type: 'single',
          options: REGION_PRY,
          showIf: pais('5'),
          terminateIf: { questionId: 'f2e-region', values: ['otro'] },
        },
        {
          id: 'f2f-region',
          text: 'F2F. ¿En qué región se encuentra? (Uruguay)',
          textPt: 'F2F. Em que região se encontra? (Uruguay)',
          type: 'single',
          options: REGION_URY,
          showIf: pais('6'),
          terminateIf: { questionId: 'f2f-region', values: ['otro'] },
        },
        {
          id: 'f2g-region',
          text: 'F2G. ¿En qué región se encuentra? (Portugal)',
          textPt: 'F2G. Em que região se encontra? (Portugal)',
          type: 'single',
          options: REGION_POR,
          showIf: pais('7'),
          terminateIf: { questionId: 'f2g-region', values: ['otro'] },
        },
        {
          id: 'f2h-region',
          text: 'F2H. ¿En qué región se encuentra? (Alemania)',
          textPt: 'F2H. Em que região se encontra? (Alemanha)',
          type: 'single',
          options: REGION_DEU,
          showIf: pais('8'),
          terminateIf: { questionId: 'f2h-region', values: ['otro'] },
        },
        {
          id: 'f3-marca',
          text: 'F3. ¿A qué compañía le realiza el mystery?',
          textPt: 'F3. A que empresa realiza o mystery?',
          type: 'single',
          options: MARCAS,
          rotate: true,
          required: true,
        },
        {
          id: 'f3-marca-otra',
          text: 'F3. Especifique la marca (Otra)',
          textPt: 'F3. Especifique a marca (Outra)',
          type: 'text',
          showIf: { questionId: 'f3-marca', values: ['13'] },
        },
        {
          id: 'f4-categoria',
          text: 'F4. ¿Su mystery corresponde a qué categoría?',
          textPt: 'F4. A que categoria corresponde o seu mystery?',
          type: 'single',
          options: [
            { value: '1', label: 'Hogares', labelPt: 'Habitações' },
            {
              value: '2',
              label: 'Negocios',
              labelPt: 'Negócios',
              showIf: pais('2', '3', '4', '5', '7'),
            },
          ],
          required: true,
        },
        {
          id: 'f5-canal',
          text: 'F5. Canal utilizado',
          textPt: 'F5. Canal utilizado',
          type: 'single',
          options: [
            { value: '1', label: 'Telefónico', labelPt: 'Telefónico' },
            {
              value: '2',
              label: 'Presencial',
              labelPt: 'Presencial',
              showIf: SI_F4_HOGAR,
            },
          ],
          required: true,
        },
      ],
    },
    {
      id: 'contacto-cero',
      title: 'Contacto cero',
      titlePt: 'Contacto zero',
      questions: [
        {
          id: 'c1-contacto',
          text: 'C1. ¿De qué manera se contacta con la compañía para coordinar la visita / pedir el llamado?',
          textPt: 'C1. De que forma contacta a empresa para coordenar a visita / pedir a chamada?',
          type: 'single',
          options: [
            {
              value: '1',
              label: 'Contacto directo con la empresa',
              labelPt: 'Contacto direto com a empresa',
            },
            {
              value: '2',
              label: 'Contacto a través de un dealer/vendedor de la empresa',
              labelPt: 'Contacto através de um dealer/vendedor da empresa',
            },
          ],
        },
        {
          id: 'c2-fecha-llamado',
          text: 'C2. Registrar la fecha y hora en que pide que lo llamen',
          textPt: 'C2. Registar a data e hora em que pede para ser contactado',
          type: 'datetime',
        },
      ],
    },
    {
      id: 'contacto-inicial',
      title: 'Contacto inicial — Telefónica',
      titlePt: 'Contacto inicial — Telefónica',
      description:
        'Speech: "Hola, ¿qué tal? Mi nombre es [nombre]. Llamo porque quería consultar para contratar un sistema de alarma monitoreada para mi [casa / negocio]".',
      descriptionPt:
        'Speech: "Olá, como está? O meu nome é [nome]. Ligo porque queria consultar para contratar um sistema de alarme monitorizado para a minha [casa / negócio]".',
      questions: [
        {
          id: 'p0-fecha-contacto-compania',
          text: 'P0. Registrar fecha y hora en que se puso en contacto con la compañía para coordinar visita / pedido de cotización telefónica',
          textPt: 'P0. Registar data e hora em que contactou a empresa para coordenar visita / pedido de cotação telefónica',
          type: 'datetime',
        },
        {
          id: 'p1-fecha-contacto',
          text: 'P1. Registrar fecha y hora del contacto',
          textPt: 'P1. Registar data e hora do contacto',
          type: 'datetime',
        },
        {
          id: 'p2-presentacion',
          text: 'P2. ¿El comercial se presentó adecuadamente (saludó, dijo su nombre y la marca) al iniciar la conversación?',
          textPt: 'P2. O comercial apresentou-se adequadamente (cumprimentou, disse o seu nome e a marca) ao iniciar a conversa?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p3-nombre',
          text: 'P3. ¿El comercial le preguntó su nombre y lo utilizó para llamarlo de forma personalizada durante la conversación?',
          textPt: 'P3. O comercial perguntou-lhe o seu nome e utilizou-o para o tratar de forma personalizada durante a conversa?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p4-respeto',
          text: 'P4. ¿El comercial le habló en todo momento de manera educada y respetuosa?',
          textPt: 'P4. O comercial falou-lhe em todo o momento de forma educada e respeitosa?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p4a-motivo',
          text: 'P4A. ¿Por qué sintió que no le habló de manera respetuosa o educada?',
          textPt: 'P4A. Por que sentiu que não lhe falou de forma respeitosa ou educada?',
          type: 'longtext',
          showIf: SI_P4_NO,
        },
        {
          id: 'p5-lenguaje',
          text: 'P5. ¿El comercial le habló utilizando un lenguaje apropiado, claro y profesional?',
          textPt: 'P5. O comercial falou-lhe utilizando uma linguagem adequada, clara e profissional?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p6-entusiasmo',
          text: 'P6. ¿El comercial demostró un entusiasmo e interés genuino al contactarlo y atender su solicitud?',
          textPt: 'P6. O comercial demonstrou entusiasmo e interesse genuíno ao contactá-lo e atender ao seu pedido?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p7-precio-respuesta',
          text: 'P7. Ante la consulta de precio ¿Cómo responde el comercial frente a la consulta inmediata de precio?',
          textPt: 'P7. Perante a consulta de preço, como responde o comercial perante a consulta imediata de preço?',
          type: 'single',
          options: P7_OPCIONES,
          hint: 'Instrucción al mystery: en medio de la conversación, debés decir de forma natural: "¿Me podría decir aproximadamente cuánto sale?"',
          hintPt: 'Instrução ao mystery: a meio da conversa, deve dizer de forma natural: "Pode dizer-me aproximadamente quanto custa?"',
        },
        {
          id: 'p8-precio-texto',
          text: 'P8. Ante la consulta de precio ¿Cómo responde el comercial frente a la consulta inmediata de precio? Detallar la respuesta textual del comercial',
          textPt: 'P8. Perante a consulta de preço, como responde o comercial perante a consulta imediata de preço? Detalhar a resposta textual do comercial',
          type: 'longtext',
        },
      ],
    },
    {
      id: 'precio-1',
      title: 'Módulo de precio 1 — Telefónica',
      titlePt: 'Módulo de preço 1 — Telefónica',
      description: 'Solo si respondió código 1 o 2 en P7.',
      descriptionPt: 'Apenas se respondeu código 1 ou 2 em P7.',
      showIf: SI_P7_PRECIO,
      questions: [
        {
          id: 'p9-precio-instalacion',
          text: 'P9. Registrar precio de instalación inicial',
          textPt: 'P9. Registar preço de instalação inicial',
          type: 'number',
          showIf: SI_P7_PRECIO,
        },
        {
          id: 'p10-precio-abono',
          text: 'P10. Registrar precio de abono mensual inicial',
          textPt: 'P10. Registar preço de mensalidade inicial',
          type: 'number',
          showIf: SI_P7_PRECIO,
        },
        {
          id: 'p11-iva',
          text: 'P11. ¿Los valores incluyen impuestos (IVA)?',
          textPt: 'P11. Os valores incluem impostos (IVA)?',
          type: 'single',
          options: SI_NO_COD,
          showIf: SI_P7_PRECIO,
        },
      ],
    },
    {
      id: 'visita',
      title: 'Visita',
      titlePt: 'Visita',
      questions: [
        {
          id: 'p12-visita',
          text: 'P12. ¿El comercial intentó coordinar una visita presencial al domicilio?',
          textPt: 'P12. O comercial tentou coordenar uma visita presencial ao domicílio?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p13-explicacion',
          text: 'P13. ¿Explicó por qué es técnicamente necesario relevar la vivienda antes de realizar una propuesta?',
          textPt: 'P13. Explicou por que é tecnicamente necessário avaliar a habitação antes de apresentar uma proposta?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p13a-fecha-visita',
          text: 'P13A. Indicar la fecha y horario en donde coordinó para recibir la visita',
          textPt: 'P13A. Indicar a data e horário em que coordenou para receber a visita',
          type: 'text',
          showIf: SI_F5_PRESENCIAL,
        },
        {
          id: 'p14-cierre-telefono',
          text: 'P14. ¿Intentó avanzar o cerrar la venta por teléfono sin ofrecer en ningún momento ir al domicilio?',
          textPt: 'P14. Tentou avançar ou fechar a venda por telefone sem oferecer em momento algum ir ao domicílio?',
          type: 'single',
          options: SI_NO_COD,
        },
      ],
    },
    {
      id: 'posicionamiento',
      title: 'Posicionamiento de la marca',
      titlePt: 'Posicionamento da marca',
      questions: [
        {
          id: 'p15-atributos',
          text: 'P15. Al hablar de la empresa, ¿qué atributos, fortalezas o argumentos utilizó el comercial para posicionar el prestigio de su marca? Describa textualmente lo que mencionó:',
          textPt: 'P15. Ao falar da empresa, que atributos, pontos fortes ou argumentos utilizou o comercial para posicionar o prestígio da sua marca? Descreva textualmente o que mencionou:',
          type: 'longtext',
        },
        {
          id: 'p16a-conversacion',
          text: 'P16A. ¿El comercial intentó generar conversación sobre temas cotidianos (no relacionados con equipos o precios) antes de entrar en la venta?',
          textPt: 'P16A. O comercial tentou gerar conversa sobre temas quotidianos (não relacionados com equipamentos ou preços) antes de entrar na venda?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p16b-temas',
          text: 'P16B. ¿Sobre qué temas conversó? Describa textualmente',
          textPt: 'P16B. Sobre que temas conversou? Descreva textualmente',
          type: 'longtext',
          showIf: SI_P16A,
        },
      ],
    },
    {
      id: 'deteccion-necesidades',
      title: 'Detección de necesidades',
      titlePt: 'Deteção de necessidades',
      questions: [
        {
          id: 'p17-diagnostico',
          text: 'P17. Durante la conversación, el comercial preguntó sobre alguno de los siguientes puntos',
          textPt: 'P17. Durante a conversa, o comercial perguntou sobre algum dos seguintes pontos',
          type: 'matrix',
          matrixColumns: SI_NO_MATRIX,
          matrixRows: [
            {
              id: 'vivienda-negocio',
              label: 'Si es una vivienda o negocio',
              labelPt: 'Se é uma habitação ou negócio',
            },
            {
              id: 'habitantes',
              label: 'Cantidad de habitantes en el hogar',
              labelPt: 'Número de habitantes no agregado familiar',
              showIf: SI_F4_HOGAR,
            },
            {
              id: 'adultos-menores',
              label: 'Presencia de adultos mayores o menores de edad',
              labelPt: 'Presença de adultos idosos ou menores de idade',
              showIf: SI_F4_HOGAR,
            },
            {
              id: 'empleados',
              label: 'Cantidad de empleados del negocio',
              labelPt: 'Número de colaboradores do negócio',
              showIf: SI_F4_NEGOCIO,
            },
            {
              id: 'incidentes',
              label: 'Incidentes previos de inseguridad en la zona o en el hogar/negocio',
              labelPt: 'Incidentes anteriores de insegurança na zona ou na habitação/negócio',
            },
            {
              id: 'soluciones-actuales',
              label: 'Soluciones de seguridad que tiene actualmente',
              labelPt: 'Soluções de segurança que possui atualmente',
            },
            { id: 'preocupacion', label: 'Nivel de preocupación', labelPt: 'Nível de preocupação' },
            {
              id: 'expectativas',
              label: 'Expectativas respecto del servicio',
              labelPt: 'Expectativas relativamente ao serviço',
            },
            {
              id: 'razones-interes',
              label: 'Razones por las que está interesado en la contratación del servicio',
              labelPt: 'Razões pelas quais está interessado na contratação do serviço',
            },
            {
              id: 'habitaciones',
              label: 'Cantidad de habitaciones/ambientes de la propiedad',
              labelPt: 'Número de divisões/ambientes da propriedade',
            },
            {
              id: 'ventanas',
              label: 'Cantidad de ventanas de la propiedad',
              labelPt: 'Número de janelas da propriedade',
            },
            {
              id: 'accesos',
              label: 'Cantidad de accesos que tiene la propiedad',
              labelPt: 'Número de acessos que tem a propriedade',
            },
            {
              id: 'tamano',
              label: 'Tamaño aproximado de la propiedad',
              labelPt: 'Dimensão aproximada da propriedade',
            },
          ],
        },
        {
          id: 'p18-otras-preguntas',
          text: 'P18. ¿El comercial realizó alguna pregunta más? Detallar textual todo lo preguntado por el comercial',
          textPt: 'P18. O comercial fez mais alguma pergunta? Detalhar textualmente tudo o que foi perguntado pelo comercial',
          type: 'longtext',
        },
        {
          id: 'p19-diagnostico-calidad',
          text: 'P19. ¿Qué tan completo y profundo le pareció el diagnóstico que hizo el comercial para evaluar la seguridad de su inmueble?',
          textPt: 'P19. Quão completo e profundo lhe pareceu o diagnóstico que fez o comercial para avaliar a segurança do seu imóvel?',
          type: 'single',
          options: [
            { value: '5', label: 'Excelente', labelPt: 'Excelente' },
            { value: '4', label: 'Bueno', labelPt: 'Bom' },
            { value: '3', label: 'Regular', labelPt: 'Regular' },
            { value: '2', label: 'Malo', labelPt: 'Mau' },
            { value: '1', label: 'Muy malo', labelPt: 'Muito mau' },
          ],
        },
        {
          id: 'p20-atencion',
          text: 'P20. ¿El comercial prestó atención y recordó los datos que usted le fue brindando durante la conversación?',
          textPt: 'P20. O comercial prestou atenção e recordou os dados que lhe foi fornecendo durante a conversa?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p21-personalizacion',
          text: 'P21. ¿El comercial logró adaptar y personalizar la propuesta final según las necesidades específicas que usted le planteó?',
          textPt: 'P21. O comercial conseguiu adaptar e personalizar a proposta final de acordo com as necessidades específicas que você lhe apresentou?',
          type: 'single',
          options: [
            { value: '5', label: 'Totalmente', labelPt: 'Totalmente' },
            { value: '4', label: 'Bastante', labelPt: 'Bastante' },
            { value: '3', label: 'Parcialmente', labelPt: 'Parcialmente' },
            { value: '2', label: 'Muy poco', labelPt: 'Muito pouco' },
            { value: '1', label: 'Nada', labelPt: 'Nada' },
          ],
        },
      ],
    },
    {
      id: 'presentacion-solucion',
      title: 'Presentación de la solución',
      titlePt: 'Apresentação da solução',
      questions: [
        {
          id: 'p22-servicio',
          text: 'P22. Describa detalladamente el servicio ofrecido por el comercial (todo lo que incluye la propuesta: equipamiento, sensores, cámaras, aplicación móvil, monitoreo y servicios complementarios):',
          textPt: 'P22. Descreva detalhadamente o serviço oferecido pelo comercial (tudo o que inclui a proposta: equipamento, sensores, câmaras, aplicação móvel, monitorização e serviços complementares):',
          type: 'longtext',
        },
        {
          id: 'p23-servicios-exclusivos',
          text: 'P23. ¿Mencionó espontáneamente por su nombre los siguientes servicios exclusivos?',
          textPt: 'P23. Mencionou espontaneamente pelo nome os seguintes serviços exclusivos?',
          type: 'matrix',
          matrixColumns: SI_NO_MATRIX,
          matrixRows: [
            {
              id: 'acuda',
              label: 'Acuda / Vigilante (respuesta física con vigilante)',
              labelPt: 'Acuda / Vigilante (resposta física com vigilante)',
              showIf: { any: [SI_F3_PROSEGUR, SI_F1_PORTUGAL] },
            },
            {
              id: 'smart',
              label: 'Prosegur Smart / App móvil',
              labelPt: 'Prosegur Smart / App móvel',
              showIf: SI_F3_PROSEGUR,
            },
            {
              id: 'camaras',
              label: 'Cámaras de monitoreo (verificación por imagen)',
              labelPt: 'Câmaras de monitorização (verificação por imagem)',
            },
            {
              id: 'contigo',
              label: 'Contigo (protección personal fuera de casa)',
              labelPt: 'Contigo (proteção pessoal fora de casa)',
              showIf: SI_F3_PROSEGUR,
            },
            {
              id: 'seguros',
              label: 'Seguros (garantías o pólizas ante robo)',
              labelPt: 'Seguros (garantias ou apólices contra roubo)',
            },
          ],
        },
        {
          id: 'p23a-explicacion',
          text: 'P23A. ¿El comercial dio explicaciones sobre en qué consisten esos servicios? ¿Cuáles?',
          textPt: 'P23A. O comercial deu explicações sobre em que consistem esses serviços? Quais?',
          type: 'longtext',
        },
        {
          id: 'p24-ejemplos',
          text: 'P24. ¿Utilizó ejemplos, catálogos, muestras físicas o demostraciones?',
          textPt: 'P24. Utilizou exemplos, catálogos, amostras físicas ou demonstrações?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p25-beneficios',
          text: 'P25. ¿Qué beneficios específicos (ej. tranquilidad, velocidad de respuesta, protección, etc.) mencionó el comercial de forma espontánea durante la conversación?',
          textPt: 'P25. Que benefícios específicos (ex. tranquilidade, rapidez de resposta, proteção, etc.) mencionou o comercial de forma espontânea durante a conversa?',
          type: 'longtext',
        },
        {
          id: 'p26-diferenciales',
          text: 'P26. ¿Qué diferenciales clave destacó el comercial para demostrar que su propuesta era la mejor opción?',
          textPt: 'P26. Que diferenciais-chave destacou o comercial para demonstrar que a sua proposta era a melhor opção?',
          type: 'longtext',
        },
        {
          id: 'p26a-equipos',
          text: 'P26A. ¿El comercial detalló sobre si el/los equipos son alquilados o tras el pago quedan como propios?',
          textPt: 'P26A. O comercial detalhou sobre se o(s) equipamento(s) são alugados ou, após o pagamento, ficam como propriedade?',
          type: 'single',
          options: [
            {
              value: '1',
              label: 'Comentó que son alquilados de manera espontánea',
              labelPt: 'Comentou que são alugados de forma espontânea',
            },
            {
              value: '2',
              label: 'Comentó que son alquilados solo luego de que le pregunté',
              labelPt: 'Comentou que são alugados apenas depois de lhe ter perguntado',
            },
            {
              value: '3',
              label: 'Comentó que quedan como propios de manera espontánea',
              labelPt: 'Comentou que ficam como propriedade de forma espontânea',
            },
            {
              value: '4',
              label: 'Comentó que quedan como propios solo luego de que le pregunté',
              labelPt: 'Comentou que ficam como propriedade apenas depois de lhe ter perguntado',
            },
          ],
        },
        {
          id: 'p26b-permanencia',
          text: 'P26B. ¿Hay un tiempo mínimo de permanencia en el servicio?',
          textPt: 'P26B. Existe um tempo mínimo de permanência no serviço?',
          type: 'single',
          options: [
            { value: '1', label: 'Sí (especificar en comentarios)', labelPt: 'Sim (especificar nos comentários)' },
            { value: '2', label: 'No', labelPt: 'Não' },
          ],
        },
        {
          id: 'p26b-permanencia-cuanto',
          text: 'P26B. ¿Cuánto tiempo mínimo de permanencia?',
          textPt: 'P26B. Qual o tempo mínimo de permanência?',
          type: 'text',
          showIf: { questionId: 'p26b-permanencia', values: ['1'] },
        },
        {
          id: 'p27-puntos',
          text: 'P27. ¿El comercial explicó activamente sobre los siguientes puntos? Marque si el elemento fue abordado por iniciativa del comercial (Espontáneo) o fue solicitado (Solicitado):',
          textPt: 'P27. O comercial explicou ativamente sobre os seguintes pontos? Marque se o elemento foi abordado por iniciativa do comercial (Espontâneo) ou foi solicitado (Solicitado):',
          type: 'matrix',
          matrixColumns: ESPONT_SOLIC,
          matrixRows: [
            {
              id: 'tipo-solucion',
              label: '¿Qué tipo de solución me recomendaría?',
              labelPt: 'Que tipo de solução me recomendaria?',
            },
            {
              id: 'monitoreo',
              label: '¿Cómo funciona el monitoreo?',
              labelPt: 'Como funciona a monitorização?',
            },
            {
              id: 'alarma',
              label: '¿Qué sucede si se activa la alarma?',
              labelPt: 'O que acontece se o alarme for ativado?',
            },
            {
              id: 'app',
              label: '¿Tienen aplicación móvil?',
              labelPt: 'Têm aplicação móvel?',
            },
            {
              id: 'instalacion',
              label: '¿Qué tiempo toma la instalación?',
              labelPt: 'Quanto tempo demora a instalação?',
            },
            {
              id: 'garantia',
              label: '¿Qué garantía ofrecen?',
              labelPt: 'Que garantia oferecem?',
            },
          ],
        },
        {
          id: 'p27-detalle-tipo-solucion',
          text: 'P27. Detallar respuesta — ¿Qué tipo de solución me recomendaría?',
          textPt: 'P27. Detalhar resposta — Que tipo de solução me recomendaria?',
          type: 'longtext',
        },
        {
          id: 'p27-detalle-monitoreo',
          text: 'P27. Detallar respuesta — ¿Cómo funciona el monitoreo?',
          textPt: 'P27. Detalhar resposta — Como funciona a monitorização?',
          type: 'longtext',
        },
        {
          id: 'p27-detalle-alarma',
          text: 'P27. Detallar respuesta — ¿Qué sucede si se activa la alarma?',
          textPt: 'P27. Detalhar resposta — O que acontece se o alarme for ativado?',
          type: 'longtext',
        },
        {
          id: 'p27-detalle-app',
          text: 'P27. Detallar respuesta — ¿Tienen aplicación móvil?',
          textPt: 'P27. Detalhar resposta — Têm aplicação móvel?',
          type: 'longtext',
        },
        {
          id: 'p27-detalle-instalacion',
          text: 'P27. Detallar respuesta — ¿Qué tiempo toma la instalación?',
          textPt: 'P27. Detalhar resposta — Quanto tempo demora a instalação?',
          type: 'longtext',
        },
        {
          id: 'p27-detalle-garantia',
          text: 'P27. Detallar respuesta — ¿Qué garantía ofrecen?',
          textPt: 'P27. Detalhar resposta — Que garantia oferecem?',
          type: 'longtext',
        },
        {
          id: 'p27a-precio-instalacion',
          text: 'P27A. Registrar el precio final de instalación inicial',
          textPt: 'P27A. Registar o preço final de instalação inicial',
          type: 'number',
          showIf: NO_P7_PRECIO_CERRADO,
        },
        {
          id: 'p27b-precio-abono',
          text: 'P27B. Registrar precio final de abono mensual inicial',
          textPt: 'P27B. Registar preço final de mensalidade inicial',
          type: 'number',
          showIf: NO_P7_PRECIO_CERRADO,
        },
        {
          id: 'p27c-iva',
          text: 'P27C. ¿Los valores incluyen impuestos (IVA)?',
          textPt: 'P27C. Os valores incluem impostos (IVA)?',
          type: 'single',
          options: SI_NO_COD,
          showIf: NO_P7_PRECIO_CERRADO,
        },
      ],
    },
    {
      id: 'negociacion',
      title: 'Negociación',
      titlePt: 'Negociação',
      questions: [
        {
          id: 'p28-objecion-caro',
          text: 'P28. Ante la objeción ("Me parece bastante caro el servicio/abono") ¿Cómo responde el comercial frente a esta objeción? Detallar la respuesta textual del comercial',
          textPt: 'P28. Perante a objeção ("Acho o serviço/mensalidade bastante caro") como responde o comercial perante esta objeção? Detalhar a resposta textual do comercial',
          type: 'longtext',
        },
        {
          id: 'p29-objecion-competencia',
          text: 'P29. Ante la objeción ("Otra empresa me ofreció un servicio más barato") ¿Cómo responde el comercial frente a esta objeción? Detallar la respuesta textual del comercial',
          textPt: 'P29. Perante a objeção ("Outra empresa ofereceu-me um serviço mais barato") como responde o comercial perante esta objeção? Detalhar a resposta textual do comercial',
          type: 'longtext',
        },
        {
          id: 'p30-justificar-valor',
          text: 'P30. ¿Intentó justificar el valor del abono antes de ofrecer descuentos?',
          textPt: 'P30. Tentou justificar o valor da mensalidade antes de oferecer descontos?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p31-promociones',
          text: 'P31. ¿Mencionó de forma proactiva promociones vigentes, bonificaciones o incentivos comerciales que impacten en la anterior propuesta?',
          textPt: 'P31. Mencionou de forma proativa promoções vigentes, bonificações ou incentivos comerciais que tenham impacto na proposta anterior?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p31a-cuotas',
          text: 'P31A. ¿Ofreció realizar el pago con cuotas?',
          textPt: 'P31A. Ofereceu realizar o pagamento em prestações?',
          type: 'single',
          options: [
            {
              value: '1',
              label: 'Sí, me ofreció cuotas con y sin interés',
              labelPt: 'Sim, ofereceu-me prestações com e sem juros',
            },
            {
              value: '2',
              label: 'Sí, me ofreció cuotas sin interés',
              labelPt: 'Sim, ofereceu-me prestações sem juros',
            },
            {
              value: '3',
              label: 'Sí, me ofreció cuotas CON interés',
              labelPt: 'Sim, ofereceu-me prestações COM juros',
            },
            {
              value: '4',
              label: 'No, no me ofreció cuotas',
              labelPt: 'Não, não me ofereceu prestações',
            },
          ],
        },
        {
          id: 'p31b-medios-pago',
          text: 'P31B. ¿Qué medios de pago aceptan? Seleccionar todos los que corresponda',
          textPt: 'P31B. Que meios de pagamento aceitam? Selecionar todos os que se aplicarem',
          type: 'multiple',
          options: [
            {
              value: '1',
              label: 'Pago en efectivo',
              labelPt: 'Pagamento em dinheiro',
            },
            {
              value: '2',
              label: 'Pago por transferencia / CBU',
              labelPt: 'Pagamento por transferência / IBAN',
            },
            {
              value: '3',
              label: 'Tarjeta de débito',
              labelPt: 'Cartão de débito',
            },
            {
              value: '4',
              label: 'Tarjeta de crédito',
              labelPt: 'Cartão de crédito',
            },
          ],
        },
        {
          id: 'p31c-diferencia-pago',
          text: 'P31C. ¿Hay alguna diferencia comercial, promocional o en los precios según el tipo de pago? ¿cuál?',
          textPt: 'P31C. Há alguma diferença comercial, promocional ou nos preços conforme o tipo de pagamento? Qual?',
          type: 'longtext',
        },
        {
          id: 'p32-tipo-promo',
          text: 'P32. ¿De qué tipo fue la promoción o incentivo ofrecido?',
          textPt: 'P32. De que tipo foi a promoção ou incentivo oferecido?',
          type: 'single',
          options: [
            { value: '1', label: 'Económica', labelPt: 'Económica' },
            {
              value: '2',
              label: 'De valor agregado (sin modificar el precio)',
              labelPt: 'De valor acrescentado (sem alterar o preço)',
            },
          ],
          showIf: SI_P31,
        },
        {
          id: 'p33-detalle-promo',
          text: 'P33. Detalle la/s promoción/es ofrecida/s por el comercial',
          textPt: 'P33. Detalhe a(s) promoção(ões) oferecida(s) pelo comercial',
          type: 'longtext',
          showIf: SI_P31,
        },
        {
          id: 'p34-precio-instalacion-promo',
          text: 'P34. Registrar precio de instalación (promoción económica)',
          textPt: 'P34. Registar preço de instalação (promoção económica)',
          type: 'number',
          showIf: SI_P32_ECONOMICA,
        },
        {
          id: 'p35-precio-abono-promo',
          text: 'P35. Registrar precio de abono mensual (promoción económica)',
          textPt: 'P35. Registar preço de mensalidade (promoção económica)',
          type: 'number',
          showIf: SI_P32_ECONOMICA,
        },
        {
          id: 'p36-iva-promo',
          text: 'P36. ¿Los valores incluyen impuestos (IVA)?',
          textPt: 'P36. Os valores incluem impostos (IVA)?',
          type: 'single',
          options: SI_NO_COD,
          showIf: SI_P32_ECONOMICA,
        },
      ],
    },
    {
      id: 'competencia',
      title: 'Competencia',
      titlePt: 'Concorrência',
      questions: [
        {
          id: 'p37-competencia',
          text: 'P37. Ante el comentario ("Aún no voy a decidir. También estoy evaluando a la competencia (mencionar nombre empresa correspondiente).") ¿Cómo responde el comercial frente a este comentario? Detallar la respuesta textual del comercial',
          textPt: 'P37. Perante o comentário ("Ainda não vou decidir. Também estou a avaliar a concorrência (mencionar nome da empresa correspondente).") como responde o comercial perante este comentário? Detalhar a resposta textual do comercial',
          type: 'longtext',
        },
        {
          id: 'p38-argumentos',
          text: 'P38. ¿Utilizó argumentos diferenciales sólidos para defender su propuesta vs. la competencia?',
          textPt: 'P38. Utilizou argumentos diferenciais sólidos para defender a sua proposta face à concorrência?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p39-habla-competencia',
          text: 'P39. ¿Cómo habló el comercial sobre la empresa de la competencia?',
          textPt: 'P39. Como falou o comercial sobre a empresa da concorrência?',
          type: 'single',
          options: [
            {
              value: '1',
              label: 'De forma positiva / respetuosa',
              labelPt: 'De forma positiva / respeitosa',
            },
            {
              value: '2',
              label: 'De forma negativa / despectiva',
              labelPt: 'De forma negativa / desdenhosa',
            },
          ],
        },
        {
          id: 'p40-rival',
          text: 'P40. Durante la charla, ¿el comercial nombró por iniciativa propia a alguna empresa específica como su principal rival o competidor? Registre qué marca mencionó y qué dijo:',
          textPt: 'P40. Durante a conversa, o comercial mencionou por iniciativa própria alguma empresa específica como o seu principal rival ou concorrente? Registe que marca mencionou e o que disse:',
          type: 'longtext',
        },
        {
          id: 'p40a-comparaciones',
          text: 'P40A. Durante la charla, ¿el comercial hace comparaciones con marcas de la competencia? ¿Cuáles? ¿Qué puntos remarca?',
          textPt: 'P40A. Durante a conversa, o comercial faz comparações com marcas da concorrência? Quais? Que pontos destaca?',
          type: 'longtext',
        },
      ],
    },
    {
      id: 'cierre',
      title: 'Cierre',
      titlePt: 'Encerramento',
      questions: [
        {
          id: 'p41-cierre',
          text: 'P41. ¿El comercial realizó un intento de cierre de venta explícito durante la interacción?',
          textPt: 'P41. O comercial realizou uma tentativa de encerramento de venda explícita durante a interação?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p42-instalacion',
          text: 'P42. ¿El comercial solicitó de forma proactiva una fecha para realizar la instalación?',
          textPt: 'P42. O comercial solicitou de forma proativa uma data para realizar a instalação?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p43-referidos',
          text: 'P43. ¿El comercial solicitó de forma proactiva referidos, independientemente de si usted contrataba o no?',
          textPt: 'P43. O comercial solicitou de forma proativa referências, independentemente de se você contratava ou não?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p44-objecion-pensar',
          text: 'P44. Ante la objeción ("No estoy seguro/a, tengo que pensarlo/meditarlo con mi pareja") ¿Cómo respondió el comercial? Describa con detalle la estrategia desarrollada por el comercial',
          textPt: 'P44. Perante a objeção ("Não tenho a certeza, tenho de pensar/refletir com o/a meu/minha companheiro/a") como respondeu o comercial? Descreva em detalhe a estratégia desenvolvida pelo comercial',
          type: 'longtext',
        },
        {
          id: 'p44a-seguir-negociando',
          text: 'P44A. Ante la objeción. ¿El comercial intentó seguir negociando? ¿Realizó un nuevo ofrecimiento? Detallar en caso de que sí.',
          textPt: 'P44A. Perante a objeção. O comercial tentou continuar a negociar? Fez uma nova proposta? Detalhar em caso afirmativo.',
          type: 'longtext',
        },
        {
          id: 'p44b-info-adicional',
          text: 'P44B. ¿El comercial le pregunta sobre qué información adicional necesitaría para definirse o qué necesitaría en general para definir su decisión?',
          textPt: 'P44B. O comercial pergunta-lhe sobre que informação adicional precisaria para se decidir ou o que precisaria em geral para definir a sua decisão?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p45-proximo-contacto',
          text: 'P45. Si no se contrata en el momento, ¿propone un próximo contacto concreto?',
          textPt: 'P45. Se não contratar no momento, propõe um próximo contacto concreto?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p46-tipo-contacto',
          text: 'P46. Describir el tipo de contacto que propone para seguimiento',
          textPt: 'P46. Descrever o tipo de contacto que propõe para acompanhamento',
          type: 'longtext',
          showIf: SI_P45,
        },
        {
          id: 'p47-cierre-conversacion',
          text: 'P47. Por favor, describa cómo se cerró la conversación con el comercial',
          textPt: 'P47. Por favor, descreva como se encerrou a conversa com o comercial',
          type: 'longtext',
        },
      ],
    },
    {
      id: 'evaluacion-experiencia',
      title: 'Evaluación de la experiencia',
      titlePt: 'Avaliação da experiência',
      questions: [
        {
          id: 'p48-satisfaccion',
          text: 'P48. ¿Cuál es su nivel de satisfacción con la atención general que le brindó el comercial durante todo el contacto?',
          textPt: 'P48. Qual é o seu nível de satisfação com o atendimento geral que o comercial lhe prestou durante todo o contacto?',
          type: 'single',
          options: ESCALA_SATISFACCION,
        },
        {
          id: 'p49-mejor',
          text: 'P49. ¿Qué fue lo mejor de la experiencia o qué aspecto le generó mayor confianza?',
          textPt: 'P49. O que foi o melhor da experiência ou que aspeto lhe gerou maior confiança?',
          type: 'longtext',
        },
        {
          id: 'p50-peor',
          text: 'P50. ¿Qué fue lo peor de la experiencia o qué aspecto le generó mayor desconfianza?',
          textPt: 'P50. O que foi o pior da experiência ou que aspeto lhe gerou maior desconfiança?',
          type: 'longtext',
        },
        {
          id: 'p51-contrataria',
          text: 'P51. Basándose exclusivamente en la gestión de este comercial, ¿contrataría el servicio?',
          textPt: 'P51. Baseando-se exclusivamente na gestão deste comercial, contrataria o serviço?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p52-porque',
          text: 'P52. ¿Por qué?',
          textPt: 'P52. Porquê?',
          type: 'longtext',
        },
      ],
    },
    {
      id: 'presencial',
      title: 'Evaluación presencial',
      titlePt: 'Avaliação presencial',
      description: 'Solo para quienes respondieron Presencial en F5.',
      descriptionPt: 'Apenas para quem respondeu Presencial em F5.',
      showIf: SI_F5_PRESENCIAL,
      questions: [
        {
          id: 'p53-horario',
          text: 'P53. ¿El asesor comercial llegó dentro del horario acordado?',
          textPt: 'P53. O assessor comercial chegou dentro do horário acordado?',
          type: 'single',
          options: [
            { value: '1', label: 'Sí', labelPt: 'Sim' },
            {
              value: '2',
              label: 'No (indicar demora abajo)',
              labelPt: 'Não (indicar atraso abaixo)',
            },
          ],
        },
        {
          id: 'p53-demora',
          text: 'P53. ¿Cuánto se demoró?',
          textPt: 'P53. Quanto tempo demorou?',
          type: 'text',
          showIf: { questionId: 'p53-horario', values: ['2'] },
        },
        {
          id: 'p54-uniforme',
          text: 'P54. ¿El comercial vestía el uniforme oficial de la empresa de manera correcta?',
          textPt: 'P54. O comercial vestia o uniforme oficial da empresa de forma correta?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p55-actitud',
          text: 'P55. ¿Cómo califica la actitud inicial demostrada por el comercial al momento de llegar a su hogar/negocio?',
          textPt: 'P55. Como avalia a atitude inicial demonstrada pelo comercial no momento de chegar à sua habitação/negócio?',
          type: 'single',
          options: [
            { value: '5', label: 'Excelente', labelPt: 'Excelente' },
            { value: '4', label: 'Buena', labelPt: 'Boa' },
            { value: '3', label: 'Regular', labelPt: 'Regular' },
            { value: '2', label: 'Mala', labelPt: 'Má' },
            { value: '1', label: 'Muy mala', labelPt: 'Muito má' },
          ],
        },
      ],
    },
    evidenciasModule(1),
  ],
};
