import { SurveySection } from '../types';
import {
  ESCALA_SATISFACCION,
  MARCAS,
  NO_P7_PRECIO_CERRADO,
  P7_OPCIONES,
  PAISES,
  REGION_ARG,
  REGION_CHI,
  REGION_COL,
  REGION_DEU,
  REGION_PER,
  REGION_POR,
  REGION_PRY,
  REGION_URY,
  SI_F1_PORTUGAL,
  SI_F3_PROSEGUR,
  SI_F4_HOGAR,
  SI_F4_NEGOCIO,
  SI_F5_PRESENCIAL,
  SI_NO_COD,
  SI_P16A,
  SI_P31,
  SI_P32_ECONOMICA,
  SI_P4_NO,
  SI_P45,
  SI_P7_PRECIO,
  pais,
} from './constants';

const SI_NO_MATRIX = [
  { value: '1', label: 'Sí' },
  { value: '2', label: 'No' },
];

const ESPONT_SOLIC = [
  { value: '1', label: 'Espontáneo' },
  { value: '2', label: 'Solicitado' },
];

export const parte1: SurveySection = {
  id: 'parte-1',
  title: 'Parte 1 — Contacto y evaluación comercial',
  description: 'Desde el screening hasta la evaluación de la experiencia (hasta P55).',
  modules: [
    {
      id: 'screening',
      title: 'Screening',
      description: 'Datos del mystery y ubicación',
      questions: [
        {
          id: 'f1-pais',
          text: 'F1. ¿En qué país realiza el mystery?',
          type: 'single',
          options: PAISES,
          required: true,
        },
        {
          id: 'f2a-region',
          text: 'F2A. ¿En qué región se encuentra? (Argentina)',
          type: 'single',
          options: REGION_ARG,
          showIf: pais('1'),
          terminateIf: { questionId: 'f2a-region', values: ['otro'] },
        },
        {
          id: 'f2b-region',
          text: 'F2B. ¿En qué región se encuentra? (Colombia)',
          type: 'single',
          options: REGION_COL,
          showIf: pais('2'),
          terminateIf: { questionId: 'f2b-region', values: ['otro'] },
        },
        {
          id: 'f2c-region',
          text: 'F2C. ¿En qué región se encuentra? (Perú)',
          type: 'single',
          options: REGION_PER,
          showIf: pais('3'),
          terminateIf: { questionId: 'f2c-region', values: ['otro'] },
        },
        {
          id: 'f2d-region',
          text: 'F2D. ¿En qué región se encuentra? (Chile)',
          type: 'single',
          options: REGION_CHI,
          showIf: pais('4'),
          terminateIf: { questionId: 'f2d-region', values: ['otro'] },
        },
        {
          id: 'f2e-region',
          text: 'F2E. ¿En qué región se encuentra? (Paraguay)',
          type: 'single',
          options: REGION_PRY,
          showIf: pais('5'),
          terminateIf: { questionId: 'f2e-region', values: ['otro'] },
        },
        {
          id: 'f2f-region',
          text: 'F2F. ¿En qué región se encuentra? (Uruguay)',
          type: 'single',
          options: REGION_URY,
          showIf: pais('6'),
          terminateIf: { questionId: 'f2f-region', values: ['otro'] },
        },
        {
          id: 'f2g-region',
          text: 'F2G. ¿En qué región se encuentra? (Portugal)',
          type: 'single',
          options: REGION_POR,
          showIf: pais('7'),
          terminateIf: { questionId: 'f2g-region', values: ['otro'] },
        },
        {
          id: 'f2h-region',
          text: 'F2H. ¿En qué región se encuentra? (Alemania)',
          type: 'single',
          options: REGION_DEU,
          showIf: pais('8'),
          terminateIf: { questionId: 'f2h-region', values: ['otro'] },
        },
        {
          id: 'f3-marca',
          text: 'F3. ¿A qué compañía le realiza el mystery?',
          type: 'single',
          options: MARCAS,
          rotate: true,
          required: true,
        },
        {
          id: 'f3-marca-otra',
          text: 'F3. Especifique la marca (Otra)',
          type: 'text',
          showIf: { questionId: 'f3-marca', values: ['13'] },
        },
        {
          id: 'f4-categoria',
          text: 'F4. ¿Su mystery corresponde a qué categoría?',
          type: 'single',
          options: [
            { value: '1', label: 'Hogares' },
            {
              value: '2',
              label: 'Negocios',
              showIf: pais('2', '3', '4', '5', '7'),
            },
          ],
          required: true,
        },
        {
          id: 'f5-canal',
          text: 'F5. Canal utilizado',
          type: 'single',
          options: [
            { value: '1', label: 'Telefónico' },
            {
              value: '2',
              label: 'Presencial',
              showIf: SI_F4_HOGAR,
            },
          ],
          required: true,
        },
      ],
    },
    {
      id: 'contacto-cero',
      title: 'Contacto cero',
      questions: [
        {
          id: 'c1-contacto',
          text: 'C1. ¿De qué manera se contacta con la compañía para coordinar la visita / pedir el llamado?',
          type: 'single',
          options: [
            { value: '1', label: 'Contacto directo con la empresa' },
            { value: '2', label: 'Contacto a través de un dealer/vendedor de la empresa' },
          ],
        },
        {
          id: 'c2-fecha-llamado',
          text: 'C2. Registrar la fecha y hora en que pide que lo llamen',
          type: 'text',
          hint: 'Fecha y hora',
        },
      ],
    },
    {
      id: 'contacto-inicial',
      title: 'Contacto inicial — Telefónica',
      description:
        'Speech: "Hola, ¿qué tal? Mi nombre es [nombre]. Llamo porque quería consultar para contratar un sistema de alarma monitoreada para mi [casa / negocio]".',
      questions: [
        {
          id: 'p1-fecha-contacto',
          text: 'P1. Registrar fecha y hora del contacto',
          type: 'text',
        },
        {
          id: 'p2-presentacion',
          text: 'P2. ¿El comercial se presentó adecuadamente (saludó, dijo su nombre y la marca) al iniciar la conversación?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p3-nombre',
          text: 'P3. ¿El comercial le preguntó su nombre y lo utilizó para llamarlo de forma personalizada durante la conversación?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p4-respeto',
          text: 'P4. ¿El comercial le habló en todo momento de manera educada y respetuosa?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p4a-motivo',
          text: 'P4A. ¿Por qué sintió que no le habló de manera respetuosa o educada?',
          type: 'longtext',
          showIf: SI_P4_NO,
        },
        {
          id: 'p5-lenguaje',
          text: 'P5. ¿El comercial le habló utilizando un lenguaje apropiado, claro y profesional?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p6-entusiasmo',
          text: 'P6. ¿El comercial demostró un entusiasmo e interés genuino al contactarlo y atender su solicitud?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p7-precio-respuesta',
          text: 'P7. Ante la consulta de precio ("¿Me podría decir aproximadamente cuánto sale?"), ¿cómo responde el comercial?',
          type: 'single',
          options: P7_OPCIONES,
          hint: 'Decir de forma natural en medio de la conversación.',
        },
        {
          id: 'p8-precio-texto',
          text: 'P8. Detallar la respuesta textual del comercial ante la consulta de precio',
          type: 'longtext',
        },
      ],
    },
    {
      id: 'precio-1',
      title: 'Módulo de precio 1 — Telefónica',
      description: 'Solo si respondió código 1 o 2 en P7.',
      questions: [
        {
          id: 'p9-precio-instalacion',
          text: 'P9. Registrar precio de instalación inicial',
          type: 'text',
          showIf: SI_P7_PRECIO,
        },
        {
          id: 'p10-precio-abono',
          text: 'P10. Registrar precio de abono mensual inicial',
          type: 'text',
          showIf: SI_P7_PRECIO,
        },
        {
          id: 'p11-iva',
          text: 'P11. ¿Los valores incluyen impuestos (IVA)?',
          type: 'single',
          options: SI_NO_COD,
          showIf: SI_P7_PRECIO,
        },
      ],
    },
    {
      id: 'visita',
      title: 'Visita',
      questions: [
        {
          id: 'p12-visita',
          text: 'P12. ¿El comercial intentó coordinar una visita presencial al domicilio?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p13-explicacion',
          text: 'P13. ¿Explicó por qué es técnicamente necesario relevar la vivienda antes de realizar una propuesta?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p13a-fecha-visita',
          text: 'P13A. Indicar la fecha y horario en donde coordinó para recibir la visita',
          type: 'text',
          showIf: SI_F5_PRESENCIAL,
        },
        {
          id: 'p14-cierre-telefono',
          text: 'P14. ¿Intentó avanzar o cerrar la venta por teléfono sin ofrecer en ningún momento ir al domicilio?',
          type: 'single',
          options: SI_NO_COD,
        },
      ],
    },
    {
      id: 'posicionamiento',
      title: 'Posicionamiento de la marca',
      questions: [
        {
          id: 'p15-atributos',
          text: 'P15. Al hablar de la empresa, ¿qué atributos, fortalezas o argumentos utilizó el comercial para posicionar el prestigio de su marca?',
          type: 'longtext',
        },
        {
          id: 'p16a-conversacion',
          text: 'P16A. ¿El comercial intentó generar conversación sobre temas cotidianos (no relacionados con equipos o precios) antes de entrar en la venta?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p16b-temas',
          text: 'P16B. ¿Sobre qué temas conversó? Describa textualmente',
          type: 'longtext',
          showIf: SI_P16A,
        },
      ],
    },
    {
      id: 'deteccion-necesidades',
      title: 'Detección de necesidades',
      questions: [
        {
          id: 'p17-diagnostico',
          text: 'P17. Durante la conversación, el comercial preguntó sobre alguno de los siguientes puntos',
          type: 'matrix',
          matrixColumns: SI_NO_MATRIX,
          matrixRows: [
            { id: 'vivienda-negocio', label: 'Si es una vivienda o negocio' },
            {
              id: 'habitantes',
              label: 'Cantidad de habitantes en el hogar',
              showIf: SI_F4_HOGAR,
            },
            {
              id: 'adultos-menores',
              label: 'Presencia de adultos mayores o menores de edad',
              showIf: SI_F4_HOGAR,
            },
            {
              id: 'empleados',
              label: 'Cantidad de empleados del negocio',
              showIf: SI_F4_NEGOCIO,
            },
            { id: 'incidentes', label: 'Incidentes previos de inseguridad en la zona o en el hogar/negocio' },
            { id: 'soluciones-actuales', label: 'Soluciones de seguridad que tiene actualmente' },
            { id: 'preocupacion', label: 'Nivel de preocupación' },
            { id: 'expectativas', label: 'Expectativas respecto del servicio' },
            { id: 'razones-interes', label: 'Razones por las que está interesado en la contratación del servicio' },
            { id: 'habitaciones', label: 'Cantidad de habitaciones/ambientes de la propiedad' },
            { id: 'ventanas', label: 'Cantidad de ventanas de la propiedad' },
            { id: 'accesos', label: 'Cantidad de accesos que tiene la propiedad' },
            { id: 'tamano', label: 'Tamaño aproximado de la propiedad' },
          ],
        },
        {
          id: 'p18-otras-preguntas',
          text: 'P18. ¿El comercial realizó alguna pregunta más? Detallar textualmente',
          type: 'longtext',
        },
        {
          id: 'p19-diagnostico-calidad',
          text: 'P19. ¿Qué tan completo y profundo le pareció el diagnóstico del comercial?',
          type: 'scale',
          scaleMin: 1,
          scaleMax: 5,
          scaleMinLabel: 'Muy malo',
          scaleMaxLabel: 'Excelente',
        },
        {
          id: 'p20-atencion',
          text: 'P20. ¿El comercial prestó atención y recordó los datos que usted le fue brindando?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p21-personalizacion',
          text: 'P21. ¿El comercial logró adaptar y personalizar la propuesta según sus necesidades?',
          type: 'scale',
          scaleMin: 1,
          scaleMax: 5,
          scaleMinLabel: 'Nada',
          scaleMaxLabel: 'Totalmente',
        },
      ],
    },
    {
      id: 'presentacion-solucion',
      title: 'Presentación de la solución',
      questions: [
        {
          id: 'p22-servicio',
          text: 'P22. Describa detalladamente el servicio ofrecido (equipamiento, sensores, cámaras, app, monitoreo, etc.)',
          type: 'longtext',
        },
        {
          id: 'p23-servicios-exclusivos',
          text: 'P23. ¿Mencionó espontáneamente por su nombre los siguientes servicios exclusivos?',
          type: 'matrix',
          matrixColumns: SI_NO_MATRIX,
          matrixRows: [
            {
              id: 'acuda',
              label: 'Acuda / Vigilante (respuesta física con vigilante)',
              showIf: { any: [SI_F3_PROSEGUR, SI_F1_PORTUGAL] },
            },
            {
              id: 'smart',
              label: 'Prosegur Smart / App móvil',
              showIf: SI_F3_PROSEGUR,
            },
            { id: 'camaras', label: 'Cámaras de monitoreo (verificación por imagen)' },
            {
              id: 'contigo',
              label: 'Contigo (protección personal fuera de casa)',
              showIf: SI_F3_PROSEGUR,
            },
            { id: 'seguros', label: 'Seguros (garantías o pólizas ante robo)' },
          ],
        },
        {
          id: 'p23a-explicacion',
          text: 'P23A. ¿El comercial dio explicaciones sobre en qué consisten esos servicios? ¿Cuáles?',
          type: 'longtext',
        },
        {
          id: 'p24-ejemplos',
          text: 'P24. ¿Utilizó ejemplos, catálogos, muestras físicas o demostraciones?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p25-beneficios',
          text: 'P25. ¿Qué beneficios específicos mencionó el comercial de forma espontánea?',
          type: 'longtext',
        },
        {
          id: 'p26-diferenciales',
          text: 'P26. ¿Qué diferenciales clave destacó el comercial?',
          type: 'longtext',
        },
        {
          id: 'p26a-equipos',
          text: 'P26A. ¿El comercial detalló si los equipos son alquilados o quedan como propios?',
          type: 'single',
          options: [
            { value: '1', label: 'Alquilados de manera espontánea' },
            { value: '2', label: 'Alquilados solo luego de que le pregunté' },
            { value: '3', label: 'Propios de manera espontánea' },
            { value: '4', label: 'Propios solo luego de que le pregunté' },
          ],
        },
        {
          id: 'p26b-permanencia',
          text: 'P26B. ¿Hay un tiempo mínimo de permanencia en el servicio?',
          type: 'single',
          options: [
            { value: '1', label: 'Sí (especificar en comentarios)' },
            { value: '2', label: 'No' },
          ],
        },
        {
          id: 'p26b-permanencia-cuanto',
          text: 'P26B. ¿Cuánto tiempo mínimo de permanencia?',
          type: 'text',
          showIf: { questionId: 'p26b-permanencia', values: ['1'] },
        },
        {
          id: 'p27-puntos',
          text: 'P27. ¿El comercial explicó activamente los siguientes puntos? Marque Espontáneo o Solicitado',
          type: 'matrix',
          matrixColumns: ESPONT_SOLIC,
          matrixRows: [
            { id: 'tipo-solucion', label: '¿Qué tipo de solución me recomendaría?' },
            { id: 'monitoreo', label: '¿Cómo funciona el monitoreo?' },
            { id: 'alarma', label: '¿Qué sucede si se activa la alarma?' },
            { id: 'app', label: '¿Tienen aplicación móvil?' },
            { id: 'instalacion', label: '¿Qué tiempo toma la instalación?' },
            { id: 'garantia', label: '¿Qué garantía ofrecen?' },
          ],
        },
        {
          id: 'p27a-precio-instalacion',
          text: 'P27A. Registrar el precio final de instalación inicial',
          type: 'text',
          showIf: NO_P7_PRECIO_CERRADO,
        },
        {
          id: 'p27b-precio-abono',
          text: 'P27B. Registrar precio final de abono mensual inicial',
          type: 'text',
          showIf: NO_P7_PRECIO_CERRADO,
        },
        {
          id: 'p27c-iva',
          text: 'P27C. ¿Los valores incluyen impuestos (IVA)?',
          type: 'single',
          options: SI_NO_COD,
          showIf: NO_P7_PRECIO_CERRADO,
        },
      ],
    },
    {
      id: 'negociacion',
      title: 'Negociación',
      questions: [
        {
          id: 'p28-objecion-caro',
          text: 'P28. Ante la objeción "Me parece bastante caro el servicio/abono", ¿cómo responde el comercial?',
          type: 'longtext',
        },
        {
          id: 'p29-objecion-competencia',
          text: 'P29. Ante la objeción "Otra empresa me ofreció un servicio más barato", ¿cómo responde el comercial?',
          type: 'longtext',
        },
        {
          id: 'p30-justificar-valor',
          text: 'P30. ¿Intentó justificar el valor del abono antes de ofrecer descuentos?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p31-promociones',
          text: 'P31. ¿Mencionó de forma proactiva promociones vigentes, bonificaciones o incentivos comerciales?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p31a-cuotas',
          text: 'P31A. ¿Ofreció realizar el pago con cuotas?',
          type: 'single',
          options: [
            { value: '1', label: 'Sí, cuotas con y sin interés' },
            { value: '2', label: 'Sí, cuotas sin interés' },
            { value: '3', label: 'Sí, cuotas con interés' },
            { value: '4', label: 'No ofreció cuotas' },
          ],
        },
        {
          id: 'p32-tipo-promo',
          text: 'P32. ¿De qué tipo fue la promoción o incentivo ofrecido?',
          type: 'single',
          options: [
            { value: '1', label: 'Económica' },
            { value: '2', label: 'De valor agregado (sin modificar el precio)' },
          ],
          showIf: SI_P31,
        },
        {
          id: 'p33-detalle-promo',
          text: 'P33. Detalle la/s promoción/es ofrecida/s por el comercial',
          type: 'longtext',
          showIf: SI_P31,
        },
        {
          id: 'p34-precio-instalacion-promo',
          text: 'P34. Registrar precio de instalación (promoción económica)',
          type: 'text',
          showIf: SI_P32_ECONOMICA,
        },
        {
          id: 'p35-precio-abono-promo',
          text: 'P35. Registrar precio de abono mensual (promoción económica)',
          type: 'text',
          showIf: SI_P32_ECONOMICA,
        },
        {
          id: 'p36-iva-promo',
          text: 'P36. ¿Los valores incluyen impuestos (IVA)?',
          type: 'single',
          options: SI_NO_COD,
          showIf: SI_P32_ECONOMICA,
        },
      ],
    },
    {
      id: 'competencia',
      title: 'Competencia',
      questions: [
        {
          id: 'p37-competencia',
          text: 'P37. Ante el comentario de que también evalúa a la competencia, ¿cómo responde el comercial?',
          type: 'longtext',
        },
        {
          id: 'p38-argumentos',
          text: 'P38. ¿Utilizó argumentos diferenciales sólidos para defender su propuesta vs. la competencia?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p39-habla-competencia',
          text: 'P39. ¿Cómo habló el comercial sobre la empresa de la competencia?',
          type: 'single',
          options: [
            { value: '1', label: 'De forma positiva / respetuosa' },
            { value: '2', label: 'De forma negativa / despectiva' },
          ],
        },
        {
          id: 'p40-rival',
          text: 'P40. ¿Nombró por iniciativa propia a alguna empresa como rival? Registre qué marca y qué dijo',
          type: 'longtext',
        },
        {
          id: 'p40a-comparaciones',
          text: 'P40A. ¿Hace comparaciones con marcas de la competencia? ¿Cuáles? ¿Qué puntos remarca?',
          type: 'longtext',
        },
      ],
    },
    {
      id: 'cierre',
      title: 'Cierre',
      questions: [
        {
          id: 'p41-cierre',
          text: 'P41. ¿El comercial realizó un intento de cierre de venta explícito?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p42-instalacion',
          text: 'P42. ¿El comercial solicitó de forma proactiva una fecha para realizar la instalación?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p43-referidos',
          text: 'P43. ¿El comercial solicitó referidos de forma proactiva?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p44-objecion-pensar',
          text: 'P44. Ante "No estoy seguro/a, tengo que pensarlo", ¿cómo respondió el comercial?',
          type: 'longtext',
        },
        {
          id: 'p44a-seguir-negociando',
          text: 'P44A. ¿Intentó seguir negociando o realizó un nuevo ofrecimiento?',
          type: 'longtext',
        },
        {
          id: 'p44b-info-adicional',
          text: 'P44B. ¿Le preguntó qué información adicional necesitaría para definirse?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p45-proximo-contacto',
          text: 'P45. Si no se contrata en el momento, ¿propone un próximo contacto concreto?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p46-tipo-contacto',
          text: 'P46. Describir el tipo de contacto que propone para seguimiento',
          type: 'longtext',
          showIf: SI_P45,
        },
        {
          id: 'p47-cierre-conversacion',
          text: 'P47. Describa cómo se cerró la conversación con el comercial',
          type: 'longtext',
        },
      ],
    },
    {
      id: 'evaluacion-experiencia',
      title: 'Evaluación de la experiencia',
      questions: [
        {
          id: 'p48-satisfaccion',
          text: 'P48. ¿Cuál es su nivel de satisfacción con la atención general del comercial?',
          type: 'single',
          options: ESCALA_SATISFACCION,
        },
        {
          id: 'p49-mejor',
          text: 'P49. ¿Qué fue lo mejor de la experiencia o qué le generó mayor confianza?',
          type: 'longtext',
        },
        {
          id: 'p50-peor',
          text: 'P50. ¿Qué fue lo peor de la experiencia o qué le generó mayor desconfianza?',
          type: 'longtext',
        },
        {
          id: 'p51-contrataria',
          text: 'P51. Basándose en la gestión de este comercial, ¿contrataría el servicio?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p52-porque',
          text: 'P52. ¿Por qué?',
          type: 'longtext',
        },
      ],
    },
    {
      id: 'presencial',
      title: 'Evaluación presencial',
      description: 'Solo para quienes respondieron Presencial en F5.',
      showIf: SI_F5_PRESENCIAL,
      questions: [
        {
          id: 'p53-horario',
          text: 'P53. ¿El asesor comercial llegó dentro del horario acordado?',
          type: 'single',
          options: [
            { value: '1', label: 'Sí' },
            { value: '2', label: 'No (indicar demora abajo)' },
          ],
        },
        {
          id: 'p53-demora',
          text: 'P53. ¿Cuánto se demoró?',
          type: 'text',
          showIf: { questionId: 'p53-horario', values: ['2'] },
        },
        {
          id: 'p54-uniforme',
          text: 'P54. ¿El comercial vestía el uniforme oficial de la empresa de manera correcta?',
          type: 'single',
          options: SI_NO_COD,
        },
        {
          id: 'p55-actitud',
          text: 'P55. ¿Cómo califica la actitud inicial del comercial al llegar a su hogar/negocio?',
          type: 'scale',
          scaleMin: 1,
          scaleMax: 5,
          scaleMinLabel: 'Muy mala',
          scaleMaxLabel: 'Excelente',
        },
      ],
    },
  ],
};
